services:
  app:
    image: remote-lab:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
  cloudflare:
    container_name: Tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
